export interface EntityField {
  name: string
  type: 'string' | 'number' | 'boolean' | 'date' | 'object' | 'array'
  required?: boolean
  description?: string
  items?: { type: string }
}

export interface EntitySchema {
  entityName: string
  tableName?: string
  tenantScoped?: boolean
  fields: EntityField[]
}

const TS_TYPE_MAP: Record<string, string> = {
  string: 'string',
  number: 'number',
  boolean: 'boolean',
  date: 'string',
  object: 'Record<string, unknown>',
  array: 'unknown[]',
}

const JAVA_TYPE_MAP: Record<string, string> = {
  string: 'String',
  number: 'Double',
  boolean: 'Boolean',
  date: 'java.time.Instant',
  object: 'java.util.Map<String, Object>',
  array: 'java.util.List<Object>',
}

export class EntityCodegen {
  generateTypeScript(schema: EntitySchema): string {
    const fields = schema.fields
      .map(f => {
        const optional = f.required ? '' : '?'
        const type = f.type === 'array' && f.items
          ? `${TS_TYPE_MAP[f.items.type] ?? 'unknown'}[]`
          : TS_TYPE_MAP[f.type] ?? 'unknown'
        const comment = f.description ? `  /** ${f.description} */\n` : ''
        return `${comment}  ${f.name}${optional}: ${type}`
      })
      .join('\n')

    return `/** Generated by Platform Entity Codegen */
export interface ${schema.entityName} {
  id: string
  tenantId: string
  createdAt: string
  updatedAt?: string
${fields}
}
`
  }

  generateJava(schema: EntitySchema): string {
    const packageName = 'com.platform.entity.generated'
    const tableName = schema.tableName ?? camelToSnake(schema.entityName)

    const fields = schema.fields
      .map(f => {
        const javaType = JAVA_TYPE_MAP[f.type] ?? 'Object'
        const nullable = f.required ? '' : '\n    @jakarta.annotation.Nullable'
        return `${nullable}\n    private ${javaType} ${f.name};`
      })
      .join('\n')

    return `package ${packageName};

import jakarta.persistence.*;
import lombok.Data;
import lombok.NoArgsConstructor;
import java.time.Instant;

/** Generated by Platform Entity Codegen */
@Entity
@Table(name = "${tableName}")
@Data
@NoArgsConstructor
public class ${schema.entityName} {

    @Id
    @GeneratedValue(strategy = GenerationType.UUID)
    private String id;

    @Column(nullable = false)
    private String tenantId;

    @Column(nullable = false)
    private Instant createdAt = Instant.now();

    private Instant updatedAt;
${fields}
}
`
  }
}

function camelToSnake(str: string): string {
  return str.replace(/([A-Z])/g, '_$1').toLowerCase().replace(/^_/, '')
}
